#!/usr/bin/env bash
# Fix the runtime environment needed by the snapped application
#
# Copyright 2025 林博仁(Buo-ren, Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# Enable the notice window if the environment variable is set
SNAP_LAUNCHER_NOTICE_ENABLED="${SNAP_LAUNCHER_NOTICE_ENABLED:-true}"

set_opts=(
    # Terminate script execution when an unhandled error occurs
    -o errexit
    -o errtrace

    # Terminate script execution when an unset parameter variable is
    # referenced
    -o nounset
)
if ! set "${set_opts[@]}"; then
    printf \
        'Error: Unable to configure the defensive interpreter behaviors.\n' \
        1>&2
    exit 1
fi

marker_file="${SNAP_USER_COMMON}/.marker.skip-collaborator-change-notice-20250627"
if ! test -e "${marker_file}" \
    && test "${SNAP_LAUNCHER_NOTICE_ENABLED}" = "true"; then
    printf \
        '=========================\nHello!\n\nI would like to inform you that I have become a collaborator of this snap and have given access to directly contribute to the packaging.\n\nIf you wish to revert the installation to the previous state you are able to do so by following the instructions at <https://github.com/brlin-tw/scrcpy-snap/releases/tag/v1.99>.\n\nBest regards,\nBuo-ren Lin <https://brlin.me>\n\nNOTE: A graphical notice is displayed with a timeout in the meantime, to skip it, set the environment variable SNAP_LAUNCHER_NOTICE_ENABLED to "false".\n=========================\n' 1>&2

    "${SNAP}/bin/collaborator-change-notice" && ret="${?}" || ret="${?}"

    case "${ret}" in
        0)
            # User pressed ENTER, avoid showing this notice window in the future
            touch "${marker_file}"
            ;;
        1)
            # User bailed out
            exit 1
            ;;
        2)
            printf "Dialog timed out, continuing...\n"
            ;;
        *)
            # Unknown error
            printf "FATAL: Unknown sdl2-notice exit status: %d\n" "${ret}" 1>&2
            exit 99
            ;;
    esac
fi

marker_file="${SNAP_USER_COMMON}/.marker.skip-rawusb-interface-notice"
if ! snapctl is-connected raw-usb; then
    printf \
        '%s: Warning: The "raw-usb" snapd security confinement interface is not connected, the OTG mode will not work.\n' \
        "${0}" \
        1>&2

    if ! test -e "${marker_file}" \
        && test "${SNAP_LAUNCHER_NOTICE_ENABLED}" = "true"; then
        printf \
            '=========================\nThe following functionality requires the "raw-usb" snapd security confinement interface to be connected:\n\nOTG mode\n\nYou may do so by running the following command in a terminal:\n\n    sudo snap connect scrcpy:raw-usb\n\nNOTE: A graphical notice is displayed with a timeout in the meantime, to skip it, set the environment variable SNAP_LAUNCHER_NOTICE_ENABLED to "false".\n=========================\n' \
            1>&2

        "${SNAP}/bin/manual-interface-notice" && ret="${?}" || ret="${?}"

        case "${ret}" in
            0)
                # User pressed ENTER, avoid showing this notice window in the future
                touch "${marker_file}"
                ;;
            1)
                # User bailed out
                exit 1
                ;;
            2)
                printf "Dialog timed out, continuing...\n"
                ;;
            *)
                # Unknown error
                printf "FATAL: Unknown sdl2-notice exit status: %d\n" "${ret}" 1>&2
                exit 99
                ;;
        esac
    fi
fi

exec "${@}"
