name: scrcpy
title: scrcpy [unofficial]

adopt-info: scrcpy

summary: Display and control your Android device

description: |
  This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.  It works on GNU/Linux, Windows and MacOS.
  This is an unofficial snap. The code of scrcpy can be found at: https://github.com/Genymobile/scrcpy
   
license: Apache-2.0
grade: stable 
confinement: strict 

base: core18

architectures:
- build-on: i386
- build-on: amd64
- build-on: arm64
- build-on: armhf

apps:
  scrcpy:
    command: usr/local/bin/scrcpy
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/android"
      MESA_GLSL_CACHE_DIR: "$SNAP_USER_DATA"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      
  adb:  
    command: usr/bin/adb
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/android/"


layout:
  /usr/local/share/scrcpy:
    symlink: $SNAP/usr/local/share/scrcpy
  /usr/local/share/icons:
    symlink: $SNAP/usr/local/share/icons
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

parts:
  scrcpy-server:
    plugin: nil
    override-pull:
      wget https://github.com/Genymobile/scrcpy/releases/download/v1.25/scrcpy-server-v1.25
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/share/scrcpy/
      cp scrcpy-server-v1.25 $SNAPCRAFT_PART_INSTALL/usr/local/share/scrcpy/scrcpy-server

  scrcpy:
    source: https://github.com/Genymobile/scrcpy.git
    plugin: meson
    meson-parameters: 
      - --buildtype=release
      - --strip 
      - -Db_lto=true
      - -Dcompile_server=false
    override-pull: |
        snapcraftctl pull
        git checkout v1.25
        snapcraftctl set-version $(git describe --tag)
    build-packages:
      - make
      - gcc
      - pkg-config
      - meson
      - ninja-build
      - libavdevice-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libsdl2-dev
      - libusb-1.0-0-dev
      - wget
    stage-packages:
      - ffmpeg
      - libsdl2-2.0-0
      - libslang2
      - libglu1-mesa
      - libusb-1.0-0
      - adb

plugs:
  adb-support:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
  opengl:
  home:
  network-bind:
  network:
  camera:
  raw-usb:
  adb:
    interface: content
    target: $SNAP/usr/bin
  

