name: scrcpy
title: scrcpy [unofficial]
summary: Display and control your Android device
description: |
  This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.  It works on GNU/Linux, Windows and MacOS.

  This is an unofficial scrcpy distribution.  Please report any issues to the snap's own issue tracker: https://github.com/sisco311/scrcpy-snap/issues

  The source code of scrcpy itself can be found at: https://github.com/Genymobile/scrcpy
contact: https://github.com/sisco311/scrcpy-snap/issues
issues: https://github.com/sisco311/scrcpy-snap/issues
source-code: https://github.com/sisco311/scrcpy-snap
website: https://github.com/sisco311/scrcpy-snap

license: Apache-2.0
grade: stable
confinement: strict
compression: lzo
version: 3.3.4

base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]

plugs:
  ffmpeg-2404:
    interface: content
    target: $SNAP/ffmpeg-platform
    default-provider: ffmpeg-2404

apps:
  scrcpy:
    command: usr/local/bin/scrcpy
    command-chain:
      - bin/scrcpy-launch
    completer: usr/local/share/bash-completion/completions/scrcpy
    desktop: usr/local/share/applications/scrcpy.desktop
    environment: &scrcpy-env
      LD_LIBRARY_PATH: ${SNAP}/ffmpeg-platform/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/android:${LD_LIBRARY_PATH}
    plugs: &scrcpy-plugs
      # For running the Android Debug Bridge (adb) and
      # connecting the Android devices over USB or TCP/IP.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md
      - adb-support
      - network
      - network-bind
      - raw-usb

      # For audio forwarding functionality
      # https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md
      - alsa
      - audio-playback
      - pulseaudio

      # For v4l2 emulation support
      # https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md
      - camera

      # For video & audio recording support
      # https://github.com/Genymobile/scrcpy/blob/master/doc/recording.md
      - home

      # For gamepad simulation support
      # https://github.com/Genymobile/scrcpy/blob/master/doc/gamepad.md
      - joystick

      # Legacy desktop support.
      # https://github.com/canonical/snapd/blob/master/interfaces/builtin/unity7.go
      - unity7
    extensions:
      - gnome

  console:
    command: usr/local/bin/scrcpy
    command-chain:
      - bin/scrcpy-launch
    completer: usr/local/share/bash-completion/completions/scrcpy
    desktop: usr/local/share/applications/scrcpy-console.desktop
    environment: *scrcpy-env
    plugs: *scrcpy-plugs
    extensions:
      - gnome

  adb:
    command: usr/bin/adb
    environment:
      # NOTE: The gnome-platform content snap entry provides libprotobuf
      # required by the adb binary.
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/android:${LD_LIBRARY_PATH}
    plugs:
      - network-bind
      - raw-usb

layout:
  # WORKAROUND:
  # libproxy.so.1 (from gnome-46-2404) has a hardcoded RUNPATH of
  # /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy for loading
  # libpxbackend-1.0.so.  Map it so the dynamic linker can resolve it.
  # https://github.com/canonical/snapcraft/pull/6054
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy:
    symlink: $SNAP/gnome-platform/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy
  # This fixes the "ERROR: Could not open icon image: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png"
  # error at runtime.
  /usr/local/share/icons:
    symlink: $SNAP/usr/local/share/icons
  # This allows scrcpy to locate the scrcpy-server binary.
  # "ERROR: '/usr/local/share/scrcpy/scrcpy-server' does not exist or is not a regular file"
  /usr/local/share/scrcpy:
    symlink: $SNAP/usr/local/share/scrcpy
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  scrcpy-server:
    plugin: nil
    build-packages:
      - curl
      - jq
    override-pull: >-
      SCRCPY_SERVER_VERSION="${SNAPCRAFT_PROJECT_VERSION}"
      "${CRAFT_PROJECT_DIR}/snap/local/scriptlets/pull-scrcpy-server.sh"
    override-build: |
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/usr/local/share/scrcpy"
      cp scrcpy-server-v* "${SNAPCRAFT_PART_INSTALL}/usr/local/share/scrcpy/scrcpy-server"

  scrcpy:
    source: https://github.com/Genymobile/scrcpy.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --strip
      - -Db_lto=true
      - -Dcompile_server=false
    build-snaps:
      - ffmpeg-2404-sdk
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PATH: /snap/ffmpeg-2404-sdk/current/usr/bin${PATH:+:$PATH}
    # https://github.com/Genymobile/scrcpy/blob/master/doc/build.md#debianubuntu
    build-packages:
      - gcc
      - git
      - libsdl2-dev
      - libusb-1.0-0-dev
      - pkg-config
      - meson
      - ninja-build

      # Provided by the FFmpeg SDK content snap
      #- libavcodec-dev
      #- libavdevice-dev
      #- libavformat-dev
      #- libavutil-dev
      #- libswresample-dev
    override-build: "${CRAFT_PROJECT_DIR}/snap/local/scriptlets/build-scrcpy.sh"
    stage-packages:
      - libasound2
      - libblas3
      - libsdl2-2.0-0
      - libslang2
      - libusb-1.0-0
    stage:
      - -usr/lib/*/libcaca++.so*
      - -usr/lib/*/libcjson_utils.so*
      - -usr/lib/*/libcairo-gobject.so*
      - -usr/lib/*/libcairo.so*
      - -usr/lib/*/libfftw3_omp.so*
      - -usr/lib/*/libfftw3_threads.so*
      - -usr/lib/*/libflite_cmu_grapheme_lang.so*
      - -usr/lib/*/libflite_cmu_grapheme_lex.so*
      - -usr/lib/*/libflite_cmu_indic_lang.so*
      - -usr/lib/*/libflite_cmu_indic_lex.so*
      - -usr/lib/*/libflite_cmu_time_awb.so*
      - -usr/lib/*/libgdk_pixbuf-*.so*
      - -usr/lib/*/libharfbuzz.so*
      - -usr/lib/*/libhwy_contrib.so*
      - -usr/lib/*/libhwy_test.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libicutest.so*
      - -usr/lib/*/libjacknet.so*
      - -usr/lib/*/libjackserver.so*
      - -usr/lib/*/liboss4-salsa.so*
      - -usr/lib/*/libpango-*.so*
      - -usr/lib/*/libpangocairo-*.so*
      - -usr/lib/*/libpangoft*.so*
      - -usr/lib/*/libpixman-*.so*
      - -usr/lib/*/libpulse-simple.so*
      - -usr/lib/*/librsvg*.so*
      - -usr/lib/*/libsphinxad.so*
      - -usr/lib/*/libtheora.so*
      - -usr/lib/*/libzvbi-chains.so*
      - -usr/share/fonts

      # Provided by the mesa-2404 content snap
      - -usr/lib/*/libdrm_amdgpu.so*
      - -usr/lib/*/libdrm_intel.so*
      - -usr/lib/*/libgallium-*.so*

  adb:
    plugin: nil
    stage-packages:
      - adb
      - android-libbase
      - android-libboringssl
      - android-libcutils
      - android-liblog
      - android-libziparchive
      - libbrotli1
      - libcap2
      - liblz4-1
      - libprotobuf32t64
      - libudev1
      - libusb-1.0-0
      - libzstd1

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*
      - -bin/sdl2-notice

  launchers-notice:
    source: snap/local/launchers/sdl2-notices
    plugin: nil
    override-build: |
      craftctl default
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/bin"

      for notice in collaborator-change-notice manual-interface-notice; do
        # NOTE: The lack of quotes around the `pkg-config` command substitution is intentional.
        gcc \
          -o "${SNAPCRAFT_PART_INSTALL}/bin/${notice}" \
          "${CRAFT_PROJECT_DIR}/snap/local/launchers/sdl2-notices/${notice}.c" \
          $(pkg-config --cflags --libs sdl2 SDL2_ttf)
      done
    build-packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
    stage:
      # WORKAROUND: Avoid the "Parts 'scrcpy' and 'launchers-notice' list the following files, but with different contents or permissions" error on armhf
      # On that architecture the libasound library is diverted to liboss4-salsa hence the contents of the file is different.
      - -usr/lib/*/libasound.so.2*

      - -usr/lib/*/libharfbuzz.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libicutest.so*
      - -usr/lib/*/libpulse-simple.so*

      # Provided by the mesa-2404 content snap
      - -usr/lib/*/libdrm_amdgpu.so*
      - -usr/lib/*/libdrm_intel.so*
      - -usr/lib/*/libgallium-*.so*

  cleanup:
    after:
      - scrcpy
      - launchers-notice
    plugin: nil
    build-snaps:
      - core24
      - mesa-2404
    override-prime: |
      set -eu

      for snap in core24 mesa-2404; do
        if ! "${CRAFT_PROJECT_DIR}/snap/local/scriptlets/drop-content-snap-duplicate-files.sh" "${snap}"; then
          printf \
              'Error: Unable to drop the duplicate files in the snap installation directory "%s".\n' \
              "${snap}" \
              1>&2
          exit 1
        fi
      done

  lp-bug-2016358-workaround:
    plugin: nil
    override-prime: |
      set -eu
      craftctl default
      mkdir -p "${CRAFT_PRIME}/"{ffmpeg-2404,gpu-2404,data-dir,data-dir/{icons,sounds,themes}}

lint:
  ignore:
    - library:
        # Required by the SDL2 library to prevent the "ERROR: Could not create renderer: Couldn't find matching render driver" error
        - usr/lib/*/libGLX_mesa.so*
        - usr/lib/*/libxcb-glx.so*

        # Workaround for the "Parts 'scrcpy' and 'launchers-notice' list the following files, but with different contents or permissions" error on armhf
        - usr/lib/*/libasound.so.2*

        # Required for core functionality at least on amd64 architecture
        # If not staged, the application will fail to start with the following error:
        # "ERROR: Could not create renderer: Couldn't find matching render driver"
        - usr/lib/*/libXxf86vm.so*
