name: scrcpy
title: scrcpy [unofficial]

adopt-info: scrcpy

summary: Display and control your Android device

description: |
  This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.  It works on GNU/Linux, Windows and MacOS.
  This is an unofficial snap. The code of scrcpy can be found at: https://github.com/Genymobile/scrcpy
   
license: Apache-2.0
grade: stable 
confinement: strict 

base: core18

architectures:
- build-on: amd64

apps:
  scrcpy:
    command: usr/local/bin/scrcpy
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/android:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      MESA_GLSL_CACHE_DIR: "$SNAP_USER_DATA"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
 
   
  adb:  
    command: usr/bin/adb
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/android/"
     

layout:
  /usr/local/share/scrcpy:
    bind: $SNAP/usr/local/share/scrcpy


parts:
  scrcpy:
    source: https://github.com/Genymobile/scrcpy.git
    plugin: meson
    meson-parameters: 
      - --buildtype=debug
      - --strip 
      - -Db_lto=true
    build-environment:
      - ANDROID_SDK_ROOT: $SNAPCRAFT_PART_BUILD
    override-pull: |
        snapcraftctl pull
        git checkout dev
        snapcraftctl set-version $(git describe --tag)
    override-build: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip

        JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        ANDROID_SDK_ROOT=$SNAPCRAFT_PART_BUILD
        ANDROID_HOME=$SNAPCRAFT_PART_BUILD
        PATH=$JAVA_HOME/bin:$PATH
        PATH=$SNAPCRAFT_PART_BUILD/tools/bin:$PATH
        export JAVA_HOME
        export ANDROID_SDK_ROOT
        export ANDROID_HOME
        export PATH

        yes | tools/bin/sdkmanager --licenses

        tools/bin/sdkmanager build-tools\;28.0.3
        tools/bin/sdkmanager platforms\;android-29
        cp $SNAPCRAFT_PROJECT_DIR/build-wrapper.sh server/scripts/build-wrapper.sh

        ANDROID_HOME=$SNAPCRAFT_PART_BUILD

        snapcraftctl build        
    build-packages:
      - make
      - gcc
      - pkg-config
      - meson
      - ninja-build
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libsdl2-dev
      - wget
      - unzip
      - openjdk-8-jre
      - openjdk-8-jdk
      - android-sdk
    stage-packages:
      - ffmpeg
      - libsdl2-2.0-0
      - libslang2
      - libglu1-mesa
      - adb
plugs:
  adb-support:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
  opengl:
  home:
  network-bind:
  network:
  adb:
    interface: content
    target: $SNAP/usr/bin
